apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/jadsonreis/sistema-nacional-cultura:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/jadsonreis/sistema-nacional-cultura:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: sistema-nacional-cultura
        chartPath: charts/sistema-nacional-cultura
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/jadsonreis/sistema-nacional-cultura"
          image.tag: "{{.DIGEST_HEX}}"
