apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
      annotations:
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: djangoapp-django
        ports:
          - containerPort: 8000
            protocol: "TCP"
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: database-url
                key: database-url
          - name: ALLOWED_HOSTS
            value: "{{ .Values.django.allowed_hosts }}"
