apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: "{{ .Chart.Name }}"
      annotations:
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: djangoapp-django
        ports:
          - containerPort: 8000
            protocol: "TCP"
        env:
          - name: DATABASE_URL
            value: "{{ .Values.django.database_url }}"
          - name: ALLOWED_HOSTS
            value: "{{ .Values.django.allowed_hosts }}"
