apiVersion: v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: 'true'
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  host: snc-jx-staging.apps.cultura.gov.br
  port:
    targetPort: 8000-tcp
  to:
    kind: Service
    name: {{ template "fullname" . }}
    weight: 100
  wildcardPolicy: None
