apiVersion: v1
kind: Route
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  host: snc-jx-staging.apps.cultura.gov.br
  to:
    kind: Service
    name: {{ template "fullname" . }}
    weight: 100
  wildcardPolicy: None
