apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
    - name: {{.Values.django.applicationPort }}-tcp
      port: {{.Values.django.applicationPort }}
      protocol: TCP
      targetPort: {{.Values.django.applicationPort }}
  selector:
    deploymentconfig: "{{ .Chart.Name }}"
  sessionAffinity: None
  type: ClusterIP

